version: '3.9'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: osrf/ros:noetic-desktop-full
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  talker:
    image: osrf/ros:noetic-desktop-full
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=talker"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always

  listener:
    image: osrf/ros:noetic-desktop-full
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=listener"
    command: stdbuf -o L rostopic echo /chatter
    networks:
      - ros
    restart: always

  rqt:
    image: osrf/ros:noetic-desktop-full
    container_name: ros_visualizer
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros_visualizer"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    user: 1000:1000
    volumes: 
      #share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
    command: rqt